In [2]:
import numpy as np

In [33]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

### 1. How many negative numbers are there?

In [9]:
len(a[a < 0])

4

### 2. How many positive numbers are there?

In [11]:
len(a[a > 0])

5

### 3. How many even positive numbers are there?

In [19]:
mask = (a % 2 == 0) & (a > 0)
len(a[mask])

3

### 4. If you were to add 3 to each data point, how many positive numbers would there be?

In [27]:
new_a = a + 3
len(new_a[new_a > 0])

10

### 5. If you squared each number, what would the new mean and standard deviation be?

In [34]:
a_squared = a ** 2

In [35]:
a_squared.mean()

74.0

In [36]:
a_squared.std()

144.0243035046516

### 6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [39]:
centering = a - a.mean()

In [40]:
centering

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [41]:
centering.mean()

0.0

### 7. Calculate the z-score for each data point.

In [50]:
z = (a - a.mean())/a.std()
z

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

### 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [54]:
import numpy as np

In [55]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### Use python's built in functionality/operators to determine the following:
* 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [57]:
sum_of_a = sum(a)
sum_of_a

55

* 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [58]:
min_of_a = min(a)
min_of_a

1

* 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [59]:
max_of_a = max(a)
max_of_a

10

* 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [68]:
mean_of_a = sum(a) / len(a)
mean_of_a

5.5

* 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [73]:
product_of_a = 1
for num in a:
    product_of_a *= num
product_of_a

3628800

* 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [76]:
squares_of_a = []
for num in a:
    squares_of_a.append(num ** 2)
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

* 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [79]:
odds_in_a = []
for num in a:
    if num % 2 == 1:
        odds_in_a.append(num)
    else:
        continue
odds_in_a

[1, 3, 5, 7, 9]

* 8 - Make a variable named evens_in_a. It should hold only the evens.

In [80]:
evens_in_a = []
for num in a:
    if num % 2 == 0:
        evens_in_a.append(num)
    else:
        continue
evens_in_a

[2, 4, 6, 8, 10]

### What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
### Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [92]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]
b

[[3, 4, 5], [6, 7, 8]]

In [95]:
matrix = np.array(b)
matrix

array([[3, 4, 5],
       [6, 7, 8]])

* 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**

In [94]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
sum_of_b

33

In [96]:
np.sum(matrix)

33

* 2 - refactor the following to use numpy. 

In [98]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])
min_of_b

3

In [99]:
np.min(matrix)

3

* 3 - refactor the following maximum calculation to find the answer with numpy.

In [102]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b

8

In [103]:
np.max(matrix)

8

* 4 - refactor the following using numpy to find the mean of b

In [104]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_b

5.5

In [105]:
np.mean(matrix)

5.5

* 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [106]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
product_of_b

20160

In [107]:
np.product(matrix)

20160

* 6 - refactor the following to use numpy to find the list of squares 

In [110]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
squares_of_b

[9, 16, 25, 36, 49, 64]

In [112]:
np.square(matrix)

array([[ 9, 16, 25],
       [36, 49, 64]])

* 7 - refactor using numpy to determine the odds_in_b

In [113]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
odds_in_b

[3, 5, 7]

In [120]:
matrix[matrix % 2 == 1]

array([3, 5, 7])

* 8 - refactor the following to use numpy to filter only the even numbers

In [121]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
evens_in_b

[4, 6, 8]

In [122]:
matrix[matrix % 2 == 0]

array([4, 6, 8])

* 9 - print out the shape of the array b.

In [127]:
matrix.shape

(2, 3)

* 10 - transpose the array b.

In [129]:
np.transpose(matrix)

array([[3, 6],
       [4, 7],
       [5, 8]])

* 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [136]:
np.reshape(matrix, (1,6))

array([[3, 4, 5, 6, 7, 8]])

* 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [137]:
np.reshape(matrix, (6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

### Setup 3

In [138]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [141]:
c = np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

* 1 - Find the min, max, sum, and product of c.

In [146]:
c.min()

1

In [147]:
c.max()

9

In [148]:
c.sum()

45

In [151]:
c.prod()

362880

* 2 - Determine the standard deviation of c.

In [152]:
c.std()

2.581988897471611

* 3 - Determine the variance of c.

In [153]:
c.var()

6.666666666666667

* 4 - Print out the shape of the array c

In [154]:
c.shape

(3, 3)

* 5 - Transpose c and print out transposed result.

In [155]:
c.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

* 6 - Get the dot product of the array c with c. 

In [159]:
c.dot(c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

* 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [167]:
(c.transpose() * c).sum()

261

* 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [168]:
(c.transpose() * c).prod()

131681894400

### Setup 4

In [176]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [177]:
d = np.array(d)
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

* 1 - Find the sine of all the numbers in d

In [175]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

* 2 - Find the cosine of all the numbers in d

In [179]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

* 3 - Find the tangent of all the numbers in d

In [180]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

* 4 - Find all the negative numbers in d

In [181]:
d[d < 0]

array([-90, -30, -45, -45])

* 5 - Find all the positive numbers in d

In [182]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

* 6 - Return an array of only the unique numbers in d.

In [184]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

* 7 - Determine how many unique numbers there are in d.

In [185]:
len(np.unique(d))

11

* 8 - Print out the shape of d.

In [186]:
d.shape

(3, 6)

In [ ]:
# Exercise 9 - Transpose and then print out the shape of d.

In [188]:
d.T.shape

(6, 3)

In [ ]:
# Exercise 10 - Reshape d into an array of 9 x 2

In [190]:
np.reshape(d, (9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])